### ISSUE TITLE
SPIKE: Determine how to build the API

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan2#12]
We should determine what module or strategy we are using for the:

* crud APIs
* read APIs for the Interra integration

**Comment by fmizzell** [comment]
the JSON API module gives a much saner output for Drupal nodes. I assume that it takes equally sane inputs but I did not confirm. As far as I am aware. JSON API works with the routes already provide for entities (Ex /node/3). @dafeder Mentioned that json_api_extras might give the user more power to create custom endpoints, but I did not go deeply into it.

**Comment by acouch** [comment]
For now we are using custom APIs for the Interra headless part and will likely use JSON API for full CRUD on endpoints.
