### ISSUE TITLE
Build dataset submission UI

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan2#182]

**Comment by drasgardian** [comment]
Any indication of what is planned for this? Is the submission of datasets and resources going to also be decoupled? Or still built on drupal entity forms?

Will this still look similar to the existing drupal 7 dkan submission interface.. and very similar to the CKAN interface? Or would we expect something very different.

This issue would be my biggest worry about the upgrade path to DKAN2 as there are a lot of content managers trained in submitting and managing datasets and resources with the existing interface, which works very well!

**Comment by janette** [comment]
@drasgardian the form will be an embedded React form inside the Drupal admin space. The form is much more straight forward than the Drupal 7 version. We are no longer storing every metadata field as a Drupal field, this was too taxing on performance. Instead the JSON will be stored as JSON and the React form will allow easy editing of the metadata.
