### ISSUE TITLE
Create a page where you can edit a dataset

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan2#298]
Remaining tasks
- [x] Messaging to show that submission was successful
- [x] Create system to define UI schema
- [x] Improve default metadata schema to be more compatible with form
- [x] Some styling
- [ ] field component tweaks
- [ ] fix date field editing (now in #312)
- [ ] tests

**Comment by fmizzell** [comment]
https://github.com/GetDKAN/dkan2/pull/299
