### ISSUE TITLE
Create entry point to create/edit dataset form

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan2#300]

**Comment by fmizzell** [comment]
After reviewing with @dafeder we thought a few more things could be done before calling this good.
- [ ] Have something show up at admin/dkan
- [ ] Remove modification from the current content list and create our own view exclusively to work with the data content type
- [ ] Remove extra properties from the schema that are not part of POD
- [ ] Make sure information on the edit form is reloaded correctly after a submission.
