### ISSUE TITLE
Move from profile to modules

### ISSUE THREAD

**Issue by kimwdavidson** [GetDKAN/dkan2#359]
Why: As modules, DKAN can be added to an existing site. 

To spec: 
- [x] do we need all modules in the same repo
- [x] what kind of dependencies do we need in the different modules 
- [x] should we still have a DKAN profile? if all you want is DKAN as a separate application

Details and tasks:
- [ ] 

Acceptance criteria:
- [ ] can spin up a site from scratch as modules

**Comment by janette** [comment]
- downstream builds would be a profile that calls dkan as a dependency
- Change https://github.com/GetDKAN/dkan2/blob/master/composer.json#L3 to 'drupal-module'
- remove global `config/install`
- config/install lives in each module that needs config
- clean up https://github.com/GetDKAN/dkan2/blob/master/dkan2.info.yml and check dependency management
- composer merge mechanism is being removed, will need a new strategy
- do we want the modules on drupal.org (food for thought)
