### ISSUE TITLE
Add custom module depenencies in composer.json

### ISSUE THREAD

**Issue by acouch** [GetDKAN/dkan2#48]
We are not able to require our custom modules correctly because we aren't identifying them in composer.json correctly. See: https://www.drupal.org/docs/develop/using-composer/managing-dependencies-for-a-custom-project

I **_think_** we might need add something like:

```json

 "../../../profiles/dkan2/modules/custom/{$name}": ["type:dkan-module"],

```

**Comment by fmizzell** [comment]
This has been resolved by dkan-tools.
