### ISSUE TITLE
"Index column size too large" db error during installation

### ISSUE THREAD

**Issue by mmenavas** [GetDKAN/dkan2#79]
I get the error message below when installing DKAN2 on Acquia. The workaround I used was to replace `varchar` with `varchar_ascii` for the fields that require 255 length in dkan_harvest.install.

**Note:** I do not have this issue when installing dkan2 locally via dktl.

<img width="768" alt="Screen Shot 2019-04-04 at 9 45 16 PM" src="https://user-images.githubusercontent.com/770699/55649029-b7179e00-5796-11e9-9c35-87475044eb2c.png">

**Comment by acouch** [comment]
Thanks. Can you make a PR?

**Comment by mmenavas** [comment]
This issue occurs in Pantheon too. #81 should take care of it.

**Comment by acouch** [comment]
I pulled this in.
